//                         ESTA FUNCION 
// RECIBE DOS PARAMETROS , UN PUNTERO AL QUE SE AÑADIRA EL DATO PASADO
// EN EL OTRO PARAMETRO QUE ES DE TIPO CHAR
// DEVUELVE UNA DIRECCION DONDE ESTA LA INFORMACION QUE SE A AÑADIDO AL VECTOR 
// EN ESTA OPERACION SE RESERVA MEMORIA CON LA FUNCION MALLOC() ,CON LO CUAL,UNA 
// VEZ SE DEJE DE UTILIZAR SE DEBE LIBERAR EL PUNTERO CON FREE()          




#ifndef STRADD_H
#define STRADD_H

char *stradd(char *v1,const char *v2);


 
 

#endif
