//                         ESTA FUNCION 
// RECIBE DOS PARAMETROS , UN PUNTERO AL QUE SE AÑADIRA EL DATO PASADO
// EN EL OTRO PARAMETRO QUE ES DE TIPO CHAR
// DEVUELVE UNA DIRECCION DONDE ESTA LA INFORMACION QUE SE A AÑADIDO AL VECTOR 
// EN ESTA OPERACION SE RESERVA MEMORIA CON LA FUNCION MALLOC() ,CON LO CUAL,UNA 
// VEZ SE DEJE DE UTILIZAR SE DEBE LIBERAR EL PUNTERO CON FREE()          

#ifndef STRADDCHAR_H
#define STRADDCHAR_H

char *straddchar(char *v,const char caracter);


#endif
